
name: carsense
description: Emulatore OBD con Dashboard, Problemi, Supporto IA e Mappa
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  http: ^1.2.3
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
